// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubaicuhjdzasdtyippgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViYWljdWhqZHphc2R0eWlwcGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MTI2NDUsImV4cCI6MjA4MzI4ODY0NX0.nnQOLubT2Wsj9Rm7n-wknLdCPcOhvmklNgUCbVbCRUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});